caller:
  name: hiieu/Meta-Llama-3-8B-Instruct-function-calling-json-mode
  load_in_8bit: True

socket:
  name: meta-llama/Llama-2-7b-hf
  load_in_8bit: True

functions:
  - name: IlyaGusev/saiga2_7b_lora
    prompt: >
      You a helpful assistant for answering questions on Russian.
    description: >
      This is the Saiga adapter trained on multiple russian datasets.
    condition: >
      Use this adapter to answer questions on Russian.
    chat_template: >
      {%- for message in messages -%}
        {{- '<s>' + message['role'] + '\n' + message['content'] + '</s>' -}}
        {%- if (loop.last and add_generation_prompt) or not loop.last -%}
          {{- '\n' -}}
        {%- endif -%}
      {%- endfor -%}
      {%- if add_generation_prompt and messages[-1]['role'] != 'assistant' -%}
        {{- '<s>assistant\n' -}}
      {% endif %}

  - name: briefai/LongShort-Llama-2-7B
    prompt: >
      You a helpful assistant for financial analysis.
    description: >
      Is a large language model fine-tuned on earnings call documents to extract financial
      KPIs from the earnings call documents.
    condition: >
      Use this adapter when users need to analyze financial data.
    chat_template: >
      {% if messages[0]['role'] == 'system' %}
        {% set loop_messages = messages[1:] %}
        {% set system_message = messages[0]['content'] %}
      {% else %}
        {% set loop_messages = messages %}
        {% set system_message = false %}
      {% endif %}
      {% for message in loop_messages %}
        {% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}
          {{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}
        {% endif %}
        {% if loop.index0 == 0 and system_message != false %}
          {% set content = '<<SYS>>\\n' + system_message + '\\n<</SYS>>\\n\\n' + message['content'] %}
        {% else %}
          {% set content = message['content'] %}
        {% endif %}
        {% if message['role'] == 'user' %}
          {{ bos_token + '[INST] ' + content.strip() + ' [/INST]' }}
        {% elif message['role'] == 'assistant' %}
          {{ ' '  + content.strip() + ' ' + eos_token }}
        {% endif %}
      {% endfor %}

